---
title: "Patagonia CRM Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
runtime: shiny
---

```{r setup}
#| include: false

# Load packages.
library(tidyverse)
library(flexdashboard)
library(shiny)
library(rsconnect)

# Import data.
customer_data <- read_csv("crm_data.csv") |> 
  mutate(age = 2022 - birth_year)
```

Sidebar {.sidebar}
------------------------------------------

```{r}
# Select the region.
selectInput(
  inputId = "region",
  label = "Region",
  choices = unique(customer_data$region)
)

# Select college_degree.
selectInput(
  inputId = "college_degree",
  label = "College Degree",
  choices = unique(customer_data$college_degree)
)
```

Row
------------------------------------------

### Age and Total Money Spent

```{r}
# Plot with reference to the region.
renderPlot({
  customer_data |> 
    filter(region == input$region, college_degree == input$college_degree) |> 
    ggplot(aes(x = total_spent, y = credit, color = gender)) +
    geom_jitter(size = 3, alpha = 0.5)
})
```

Row
------------------------------------------

### Average Income

```{r}
# Add a value box (numeric summary) to the empty environment.
renderValueBox({
  # Compute the average income.
  avg_income <- customer_data |> 
    filter(region == input$region, college_degree == input$college_degree) |> 
    summarize(avg_income = mean(income)) |> 
    pull()
  
  # Print the average income in a value box.
  valueBox(round(avg_income), icon = "fa-money")
})
```

### Average Credit Score

```{r}
# Add a value box (numeric summary) to the empty environment.
renderValueBox({
  # Compute the average credit.
  avg_credit <- customer_data |> 
    filter(region == input$region, college_degree == input$college_degree) |> 
    summarize(avg_credit = mean(credit)) |> 
    pull()
  
  # Print the average credit in a value box.
  valueBox(round(avg_credit), icon = "fa-bank")
})
```

### Median Age

```{r}
# Add a value box (numeric summary) to the empty environment.
renderValueBox({
  # Compute the median age.
  med_age <- customer_data |> 
    filter(region == input$region, college_degree == input$college_degree) |> 
    summarize(med_age = median(age)) |> 
    pull()
  
  # Print the median age in a value box.
  valueBox(med_age, icon = "fa-address-book")
})
```

